# Site settings
title: Emily Littleworth
email: emlittleworth@gmail.com
url: "http://emilylittleworth.com"
twitter_username: emlittleworth
github_username:  emlittleworth
linkedin_username: emlittleworth